site_name: TU/e Supercomputing Center
site_url: https://supercomputing.tue.nl/
docs_dir: &base_path docs
repo_name: HPC-TUE/supercomputing.tue.nl
repo_url: https://github.com/HPC-TUE/supercomputing.tue.nl
edit_uri: edit/main/docs/
theme:
  name: material
  custom_dir: overrides
  font: false
  language: en
  logo: assets/images/logo.svg
  favicon: assets/images/favicon.ico
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - toc.follow
#    - toc.integrate
    - search
    - search.suggest
    - search.highlight
    - search.share
    - announce.dismiss
    - content.action.edit
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
    - content.tooltips
    - content.footnote.tooltips
  palette:
#    - media: "(prefers-color-scheme: dark)"
#      scheme: slate
#      primary: custom
#      accent: custom
#      toggle:
#        icon: material/brightness-4
#        name: Switch to light mode
    - scheme: tuesc
      primary: custom
      accent: custom
#      toggle:
#        icon: material/brightness-7
#        name: Switch to dark mode
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye
extra_css:
  - assets/css/scheme.css
  - assets/css/site.css
plugins:
  - awesome-nav
  - glightbox
  - git-revision-date-localized:
      enabled: !ENV [CI, false]
      fallback_to_build_date: true
      enable_creation_date: true
      timezone: Europe/Amsterdam
      type: timeago
  - meta
  - minify:
      enabled: !ENV [CI, false]
      minify_html: true
      htmlmin_opts:
        remove_comments: true
      minify_js: true
      minify_css: true
      cache_safe: true
      css_files:
        - assets/css/scheme.css
        - assets/css/site.css
  - rss:
      enabled: !ENV [CI, false]
      match_path: 'blog.posts.(news|events|maintenance).[0-9]+..*'
      date_from_meta:
        as_creation: date
      categories:
        - categories
  - scc/blog:
      post_excerpt_max_authors: 10
      post_url_date_format: yyyy
  - scc/blog:
      blog_dir: documentation/kb
      post_dir: "{blog}/articles"
      main: false
      archive: false
      post_url_format: "{categories}/{slug}"
  - scc/meta
  - search:
      lang: en
  - social:
      enabled: !ENV [CI, false]
      cards: false
      cards_layout_options:
        background_color: "#1a1a1a"
        color: "#fafafa"
  - tags:
      tags: false
watch:
  - overrides
  - layouts
markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: false
  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      base_path: *base_path
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
copyright: TU/e Supercomputing Center
extra:
  analytics:
    provider: google
    property: GTM-MSH9NTC5
  social:
    - name: TU/e Supercomputing Center at LinkedIn
      icon: material/linkedin
      short: /in/supercomputing
      link: https://www.linkedin.com/in/supercomputing/
    - name: TU/e Supercomputing Center at MS Teams
      icon: material/microsoft-teams
      short: TU/e SCC
      link: https://teams.microsoft.com/l/team/19:7830cc8a6f244d6689a374c60673b43c%40thread.tacv2/conversations?groupId=a07b9e15-8538-4889-8610-502177c36dc7&tenantId=cc7df247-60ce-4a0f-9d75-704cf60efc64
  consent:
    title: Our website uses cookies
    description: >-
      It allows us to offer you the best website experience. By accepting the cookies, 
      you allow us to use these cookies to optimize the user-friendliness of our website, 
      to analyze website usage, and to support our marketing activities.
    actions: [accept, reject, manage]
